"""Generate a deterministic, SYNTHETIC sample MRU dataset for demos and tests.

Produces a CSV with a timestamp and heave/pitch motion channels for the
illustrative reference SCR sea state. Every value is SYNTHETIC (JONSWAP + an
illustrative RAO) and the file header says so - it is a demo/fallback, never a
stand-in for measured MRU data.

Run (from the repo root, with the core installed):
    python data/samples/generate_sample_mru.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from scr_twin_core.synthetic import default_heave_rao, synthetic_mru_motion

OUT = Path(__file__).with_name("synthetic_mru_reference_scr.csv")

# Sea state / record parameters (documented, reproducible).
DURATION_S = 1800.0  # 30 min stationary window
FS_HZ = 4.0
HS_M = 3.5
TP_S = 11.0
GAMMA = 2.5
SEED = 20240705


def _pitch_rao(f: np.ndarray) -> np.ndarray:
    """Illustrative pitch RAO magnitude [deg/m of wave], peaked in the wave band."""
    fn = 1.0 / 14.0
    r = f / fn
    return 2.5 / np.sqrt((1.0 - r**2) ** 2 + (2.0 * 0.15 * r) ** 2)


def main() -> None:
    heave = synthetic_mru_motion(
        duration=DURATION_S, fs=FS_HZ, hs=HS_M, tp=TP_S, gamma=GAMMA, seed=SEED,
        rao=default_heave_rao,
    )
    pitch = synthetic_mru_motion(
        duration=DURATION_S, fs=FS_HZ, hs=HS_M, tp=TP_S, gamma=GAMMA, seed=SEED + 1,
        rao=_pitch_rao,
    )
    import pandas as pd

    df = pd.DataFrame(
        {"time_s": heave.time, "heave_m": heave.heave, "pitch_deg": pitch.heave}
    )
    # Provenance as comment lines, then a real CSV header row + data.
    with open(OUT, "w", newline="", encoding="utf-8") as f:
        f.write("# SYNTHETIC MRU DATA - generated by generate_sample_mru.py (NOT measured).\n")
        f.write(f"# seed={SEED} fs={FS_HZ}Hz duration={DURATION_S}s Hs={HS_M}m Tp={TP_S}s gamma={GAMMA}\n")
        df.to_csv(f, index=False, float_format="%.6e")
    print(f"wrote {OUT} ({len(df)} rows)")


if __name__ == "__main__":
    main()
